services:
  mayra-jewelry:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mayra-jewelry
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # - ${GOPATH}/pkg/mod:/go/pkg/mod
      - mayra-code:/app

volumes:
  mayra-code:

x-mutagen:
  sync:
    code:
      alpha: "."
      beta: "volume://mayra-code"
      mode: "two-way-resolved"
      ignore:
        vcs: true
        paths:
          - "/tmp"
          - "/node_modules"
          - ".env"
